# Computation Notebook 

This notebook is meant to show and compare the computational costs with the grid-based approach (searching all possible gridpoints) versus the gridless approach (binary search) to find decision boundary points. 

We show the times that are associated with each of these.

In [1]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
import numpy as np 
import pandas as pd
import warnings
import random 
from sklearn.utils import resample

random.seed(0)
warnings.filterwarnings('ignore', category=UserWarning)

import os
import sys
nb_dir = os.path.split(os.getcwd())[0]
if nb_dir not in sys.path:
    sys.path.append(nb_dir)

# Experiments of the Computation Costs for Grid-based Approach (Logistic Regression with Numba)

$\textbf{ Logistic Regression with Grid-based Method }$ -- 50 features

Resolution: $R = 15$ ($15^{50}$ points), Memory Error (Maximum allowed dimension exceeded), 0 boundary points found

Resolution: $R = 10$ ($10^{50}$ points), Memory Error (Maximum allowed dimension exceeded), 0 boundary points found

$\textbf{ Logistic Regression with Grid-based Method }$ -- 10 features

Resolution: $R = 15$ ($15^{15}$ points), 42 Terabyte Memory Error, 0 boundary points found

Resolution: $R = 10$ ($10^{10}$ points), 745 Gigabytes Memory Error, 0 boundary points found


$\textbf{ Logistic Regression with Grid-based Method }$ -- 2 features

Resolution: $R = 150$ ($150^2 = 22,500$ points searched), 28.1 seconds runtime, 454 boundary points found

Resolution: $R = 100$ ($100^2 = 10,000$ points searched) 5.5 seconds runtime, 104 boundary points found

In [2]:
from files.grid_optimal_point import optimal_point

In [3]:
X, y = make_classification(n_samples=2000, n_features=2, n_informative=2, n_redundant=0, random_state=42, n_classes=2)
model = LogisticRegression()
y = y.reshape(-1,1)
df1 = pd.DataFrame(data=np.hstack((X,y)))

In [4]:
df1.head(n=10)

0         1    2
0  0.800062 -0.957489  1.0
1  1.187099  1.159787  1.0
2  0.154512  1.217520  0.0
3  0.179014 -0.852832  1.0
4 -0.735827 -0.245366  0.0
5  0.039487  1.320957  1.0
6 -1.482199  0.419738  0.0
7 -0.622829 -0.803223  0.0
8  0.965721 -1.068587  1.0
9  0.798459 -1.022348  1.0

In [5]:
optimal_point(df1, model=model, desired_class=0, original_class=1, resolution=150, chosen_row=1, point_epsilon=0.1, epsilon=0.07, plot=False)

/mnt/c/Users/Compuworld/drexel_research_2024_2025/Docs/files/common_functions.py:425: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  balanced_dataset = pd.concat([balanced_dataset, upsampled_class], ignore_index=True)


Class counts:
 2
1    1000
0    1000
Name: count, dtype: int64
Fitting model...
Model training complete.
boundary points started generation...
boundary points finished.
Number of boundary points
(311, 2)
Finding the closest point from the contour line to the point...
Finding the closest point from the contour line to the point.
[[1.07092306 0.87624128]]
[[-1.16018181  0.00452233]]


[np.float64(-0.05536678064834133), np.float64(1.163749815503608)]

In [62]:
optimal_point(df1, model=model, desired_class=0, original_class=1, resolution=100, chosen_row=1, point_epsilon=0.1, epsilon=0.07)

C:\Users\Compuworld\AppData\Local\Temp\ipykernel_26024\3739720189.py:17: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  balanced_dataset = pd.concat([balanced_dataset, upsampled_class], ignore_index=True)


Class counts:
 2
1    1000
0    1000
Name: count, dtype: int64
Fitting model...
Model training complete.
boundary points started generation...
boundary points finished.
(104, 2)
Finding the closest point from the contour line to the point...
Finding the closest point from the contour line to the point.
[[1.07092411 1.09801295]]
[[-1.15887253 -0.03919662]]


[-0.05396585561956102, 1.116748769377007]

In [6]:
X, y = make_classification(n_samples=2000, n_features=10, n_informative=10, n_redundant=0, random_state=42, n_classes=2)
model = LogisticRegression()
y = y.reshape(-1,1)
df2 = pd.DataFrame(data=np.hstack((X,y)))

In [7]:
df2.head(n=10)

0         1         2         3         4         5         6   \
0  1.990620 -2.921959 -5.689956  3.173745 -4.393239  0.538239 -0.962650   
1  1.342356  0.942957  3.057782  0.059667 -0.611317 -0.985521  0.323851   
2 -1.063987  2.185873 -2.230002  1.095676 -0.240747 -1.776678 -4.165090   
3 -4.852159  1.297380  3.466596  4.114327 -4.004815 -0.591707  2.035825   
4  0.033975 -0.181000  0.438378 -1.506810 -0.503984  2.442108 -0.408010   
5  2.770680 -0.667671 -2.726522  1.778277  3.033320  1.052492  1.810689   
6 -1.375939  0.889744 -0.487178  0.394568 -1.553368  2.302102 -0.134183   
7  0.060123 -2.850018 -1.808885  1.649850  0.827631 -0.681723  3.049334   
8  1.735121  4.266722  0.767749 -2.012636  2.538945 -4.960979  2.908603   
9  0.436313  1.826231 -0.232626 -0.570040  1.101895  0.658344 -0.079847   

         7         8         9    10  
0 -3.024594 -0.837913 -1.944185  1.0  
1  0.853719  1.741036  2.069323  1.0  
2 -0.122159  0.688403  1.401783  1.0  
3  3.118117 -0.996438  1.465570  1.0  
4  1.722336  2.563095 -3.228898  1.0  
5 -3.730430 -2.032935  2.371080  0.0  
6  1.340100  0.741324  0.554025  1.0  
7 -1.560887 -0.029848  0.037102  0.0  
8 -6.451668  2.723697  0.785976  0.0  
9 -2.158960  0.985347  0.426746  0.0

In [9]:
optimal_point(df2, model=model, desired_class=0, original_class=1, resolution=15, chosen_row=1, point_epsilon=0.1, epsilon=0.07)

Class counts:
 10
1    1005
0    1005
Name: count, dtype: int64
Fitting model...
Model training complete.
boundary points started generation...
Not enough memory to generate a grid with 15^10 number of points


c:\Users\Compuworld\drexel_research_2024_2025\files\common_functions.py:422: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  balanced_dataset = pd.concat([balanced_dataset, upsampled_class], ignore_index=True)


UnboundLocalError: cannot access local variable 'boundary_points' where it is not associated with a value

In [69]:
optimal_point(df2, model=model, desired_class=0, original_class=1, resolution=10, chosen_row=1, point_epsilon=0.1, epsilon=0.07)

Class counts:
 10
1    1005
0    1005
Name: count, dtype: int64
Fitting model...
Model training complete.
boundary points started generation...
Not enough memory to generate a grid with 10^10 number of points


C:\Users\Compuworld\AppData\Local\Temp\ipykernel_26024\3739720189.py:17: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  balanced_dataset = pd.concat([balanced_dataset, upsampled_class], ignore_index=True)


In [10]:
X, y = make_classification(n_samples=2000, n_features=50, n_informative=50, n_redundant=0, random_state=42, n_classes=2)
model = LogisticRegression()
y = y.reshape(-1,1)
df3 = pd.DataFrame(data=np.hstack((X,y)))

In [11]:
df3.head(n=10)

0          1         2         3          4         5         6   \
0   1.498960   1.740244  2.852685  0.483250   2.629995  2.421617 -0.605894   
1  11.043912   1.305697 -4.162067  7.062152  10.188181 -5.216963  0.869844   
2   1.699169  -8.643500  5.242382  4.438892  -0.622756  0.935984  5.435414   
3   2.454609   4.730429 -1.116898 -5.399067  -1.189977 -1.699942  3.976442   
4   0.400635  -2.403447  0.837233  1.377394   4.496939 -3.341007  0.073394   
5   2.545557  10.026681  2.393387 -2.369646  -0.269603  0.979513  1.661028   
6  -1.593692   3.824784 -0.908609  2.942972   3.894036  3.413266  1.553961   
7   3.681587  -4.058194  2.212674 -0.258745  -1.462812 -3.909477  3.147509   
8   3.159427  -4.605655  3.807224  0.908897  10.764171 -3.639272 -3.447677   
9   1.633173   3.666814 -0.403462 -3.688655   6.947526 -3.817231 -3.978926   

         7          8         9   ...         41        42        43  \
0  3.277559  -4.254546  0.657476  ...   1.655511 -5.087583 -1.446621   
1  6.395281 -14.499055 -2.626266  ...  -1.371640 -2.518497 -1.723985   
2  3.986439   5.502292  2.903077  ...  -2.215406  5.446412  4.758631   
3  4.936787   8.205961 -0.676943  ...   1.208745 -1.076917 -1.119831   
4 -1.536370  -2.858345  1.481029  ... -11.217268  4.594756  4.380212   
5  0.861730  -1.251917  6.446719  ...  -2.476918 -1.510854 -1.485889   
6 -7.739468   2.197464  0.299972  ...  -0.561935  4.208008  7.395545   
7 -4.719408  -6.281705  3.619122  ...  -7.608988  0.617678  3.293293   
8  4.983319   5.159230  1.414902  ...   3.107829  4.186121  0.839391   
9  0.316689   5.102090 -3.981173  ... -10.370874  3.227933 -9.640087   

         44        45         46        47         48        49   50  
0  5.061929 -4.813585  -8.186449  3.429404 -10.006712  3.805926  1.0  
1 -2.125003 -2.793473  -0.928793 -7.307003  -9.042577 -1.534964  1.0  
2  1.948837 -2.243126 -10.913266  2.709645  -5.339160 -5.383915  1.0  
3 -0.596468  3.882105   4.146733  5.821566   5.414165  1.990073  0.0  
4  3.271706 -4.442203  -5.418086  0.023346  -2.009643 -0.778441  1.0  
5  2.787948 -1.637217   4.217302  2.820862   3.438934  0.154469  0.0  
6  4.576173  0.815791  -3.038333 -1.339261   7.664257 -2.959643  0.0  
7  2.675376 -6.577331  -4.715912 -3.124655  -1.824645 -3.132426  1.0  
8 -1.925860 -2.886895  -3.350357 -6.439152  -1.476345 -2.515509  1.0  
9  5.534013 -3.588567   3.703978  3.262374   3.831146  3.089794  0.0  

[10 rows x 51 columns]

In [12]:
optimal_point(df3, model=model, desired_class=0, original_class=1, resolution=15, chosen_row=1, point_epsilon=0.1, epsilon=0.07)

Class counts:
 50
1    1001
0    1001
Name: count, dtype: int64
Fitting model...
Model training complete.
boundary points started generation...


c:\Users\Compuworld\drexel_research_2024_2025\files\common_functions.py:422: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  balanced_dataset = pd.concat([balanced_dataset, upsampled_class], ignore_index=True)


ValueError: Maximum allowed dimension exceeded

In [72]:
optimal_point(df3, model=model, desired_class=0, original_class=1, resolution=10, chosen_row=1, point_epsilon=0.1, epsilon=0.07)

Class counts:
 50
1    1001
0    1001
Name: count, dtype: int64
Fitting model...
Model training complete.
boundary points started generation...


C:\Users\Compuworld\AppData\Local\Temp\ipykernel_26024\3739720189.py:17: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  balanced_dataset = pd.concat([balanced_dataset, upsampled_class], ignore_index=True)


ValueError: Maximum allowed dimension exceeded

# Experiments of the Computation Costs for SSBA Approach - CPU (Logistic Regression)

$\textbf{ Logistic Regression with SSBA Method }$ -- 50 features

Search: $S = 50,000,000$, $T = $500,000$ $, 2 minutes 52 second runtime, $500,000$ boundary points found

Search: $S = 10,000,000$, $T = 100,000$, 33.2 second runtime, $100,000$ boundary points found

Search: $S = 1,000,000$, $T = 10,000$, 3.4 second runtime, $10,000$ boundary points found

$\textbf{ Logistic Regression with SSBA Method }$ -- 10 features

Search: $S = 25,000,000$, $T = 250,000$, 1 minute 23 second runtime, $250,000$ boundary points found

Search: $S = 10,000,000$, $T = 100,000$, 1 minute 1 second runtime, $100,000$ boundary points found

Search: $S = 1,000,000$, $T = 10,000$, 6.2 second runtime, $10,000$ boundary points found


$\textbf{ Logistic Regression with SSBA Method }$ -- 2 features

Search: $S = 25,000,000$, $T = 250,000$, 1 minute 56 seconds runtime, $250,000$ boundary points found

Search: $S = 10,000,000$, $T = 100,000$, ~58.0 seconds runtime, $100,000$ boundary points found

Search: $S = 150,000$, $T = 1,500$, 0.9 seconds runtime, $1,500$ boundary points found

Search: $S = 50,000$, $T = 500$, 0.3 seconds runtime, $500$ boundary points found

In [13]:
from files.binary_search_optimal_point import optimal_point

In [14]:
optimal_point(df1, model=model, desired_class=0, original_class=1, threshold=500, chosen_row=1, point_epsilon=1e-6, epsilon=0.07)

c:\Users\Compuworld\drexel_research_2024_2025\files\common_functions.py:422: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  balanced_dataset = pd.concat([balanced_dataset, upsampled_class], ignore_index=True)


Class counts:
 2
1    1000
0    1000
Name: count, dtype: int64
Fitting model...
Model training complete.
boundary points started generation...
boundary points finished.
(500, 2)
Finding the closest point from the contour line to the point...
Finding the closest point from the contour line to the point.
[[1.07091374 1.09092245]]
[[-1.17201521 -0.05214123]]


[-0.06802850227118462, 1.102905126960038]

In [36]:
optimal_point(df1, model=model, desired_class=0, original_class=1, threshold=1500, chosen_row=1, point_epsilon=1e-6, epsilon=0.07)

C:\Users\Compuworld\AppData\Local\Temp\ipykernel_26024\3739720189.py:17: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  balanced_dataset = pd.concat([balanced_dataset, upsampled_class], ignore_index=True)


Class counts:
 2
1    1000
0    1000
Name: count, dtype: int64
Fitting model...
Model training complete.
boundary points started generation...
boundary points finished.
(1500, 2)
(1499, 2)
Finding the closest point from the contour line to the point...
Finding the closest point from the contour line to the point.
[[1.07091363 1.09232891]]
[[-1.17214831 -0.04891994]]


[-0.06817092497733879, 1.1063504969422844]

In [ ]:
optimal_point(df1, model=model, desired_class=0, original_class=1, threshold=10000,  chosen_row=1, point_epsilon=1e-6, epsilon=1e-3)

C:\Users\Compuworld\AppData\Local\Temp\ipykernel_26024\3739720189.py:17: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  balanced_dataset = pd.concat([balanced_dataset, upsampled_class], ignore_index=True)


Class counts:
 2
1    1000
0    1000
Name: count, dtype: int64
Fitting model...
Model training complete.
boundary points started generation...
boundary points finished.
(10000, 2)
(9930, 2)
Finding the closest point from the contour line to the point...
Finding the closest point from the contour line to the point.
[[1.07091361 1.09265831]]
[[-1.17217655 -0.04822329]]


[-0.0682011453870428, 1.1070955780639113]

In [30]:
optimal_point(df1, model=model, desired_class=0, original_class=1, threshold=100000,  chosen_row=1, point_epsilon=1e-6, epsilon=1e-3)

Class counts:
 2
1    1000
0    1000
Name: count, dtype: int64
Fitting model...
Model training complete.
boundary points started generation...


C:\Users\Compuworld\AppData\Local\Temp\ipykernel_1072\3739720189.py:17: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  balanced_dataset = pd.concat([balanced_dataset, upsampled_class], ignore_index=True)


[0.49914333 0.50085667]
boundary points finished.
(100000, 2)
(93892, 2)
Finding the closest point from the contour line to the point...
Finding the closest point from the contour line to the point.
[[1.00185992 1.01336927]]
[[-1.16506425 -0.08192634]]


[0.019867501974112578, 1.0767655269234389]

In [15]:
optimal_point(df1, model=model, desired_class=0, original_class=1, threshold=250000,  chosen_row=1, point_epsilon=1e-4, epsilon=1e-3)

c:\Users\Compuworld\drexel_research_2024_2025\files\common_functions.py:422: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  balanced_dataset = pd.concat([balanced_dataset, upsampled_class], ignore_index=True)


Class counts:
 2
1    1000
0    1000
Name: count, dtype: int64
Fitting model...
Model training complete.
boundary points started generation...
boundary points finished.
(250000, 2)
Finding the closest point from the contour line to the point...
Finding the closest point from the contour line to the point.
[[1.00185492 1.02061952]]
[[-1.17187037 -0.0520206 ]]


[0.013054584144625236, 1.1066939179483033]

In [28]:
optimal_point(df1, model=model, desired_class=0, original_class=1, threshold=1000000,  chosen_row=1, point_epsilon=1e-4, epsilon=1e-3)

C:\Users\Compuworld\AppData\Local\Temp\ipykernel_1072\3739720189.py:17: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  balanced_dataset = pd.concat([balanced_dataset, upsampled_class], ignore_index=True)


Class counts:
 2
1    1000
0    1000
Name: count, dtype: int64
Fitting model...
Model training complete.
boundary points started generation...
[0.49913905 0.50086095]
boundary points finished.
(793845, 2)
(501549, 2)
Finding the closest point from the contour line to the point...
Finding the closest point from the contour line to the point.
[[1.00185992 1.01336927]]
[[-1.16506425 -0.08192634]]


[0.019867501974112578, 1.0767655269234389]

In [ ]:
optimal_point(df2, model=model, desired_class=0, original_class=1, threshold=10000,  chosen_row=1, point_epsilon=1e-6, epsilon=1e-3)

C:\Users\Compuworld\AppData\Local\Temp\ipykernel_26024\3739720189.py:17: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  balanced_dataset = pd.concat([balanced_dataset, upsampled_class], ignore_index=True)


Class counts:
 10
1    1005
0    1005
Name: count, dtype: int64
Fitting model...
Model training complete.
boundary points started generation...
boundary points finished.
(10000, 10)
(9866, 10)
Finding the closest point from the contour line to the point...
Finding the closest point from the contour line to the point.
[[1.05163249 1.07644004 1.53825421 1.17039462 1.06679043 1.0428281
  1.05923151 1.07388643 1.07460187 1.0728924 ]]
[[ 0.05725502 -0.16714804 -0.00328508 -0.01165794  0.33237778  0.03837891
   0.09836393 -0.27631715 -0.23351414 -0.37093554]]


[1.402567678533219,
 0.7630316648350698,
 3.0527290312584814,
 0.04602232628535625,
 -0.25673937539030584,
 -0.9454981360481078,
 0.4280408699922583,
 0.5569860161657479,
 1.4901011094673016,
 1.6713487487852436]

In [ ]:
optimal_point(df2, model=model, desired_class=0, original_class=1, threshold=100000,  chosen_row=1, point_epsilon=1e-6, epsilon=0.07)

c:\Users\Compuworld\drexel_research_2024_2025\files\common_functions.py:422: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  balanced_dataset = pd.concat([balanced_dataset, upsampled_class], ignore_index=True)


Class counts:
 10
1    1005
0    1005
Name: count, dtype: int64
Fitting model...
Model training complete.
boundary points started generation...


In [50]:
optimal_point(df2, model=model, desired_class=0, original_class=1, threshold=250000,  chosen_row=1, point_epsilon=1e-3, epsilon=0.01)

C:\Users\Compuworld\AppData\Local\Temp\ipykernel_26024\3739720189.py:17: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  balanced_dataset = pd.concat([balanced_dataset, upsampled_class], ignore_index=True)


Class counts:
 10
1    1005
0    1005
Name: count, dtype: int64
Fitting model...
Model training complete.
boundary points started generation...
boundary points finished.
(250000, 10)
(181933, 10)
Finding the closest point from the contour line to the point...
Finding the closest point from the contour line to the point.
[[1.02523961 1.01675174 1.01588534 1.01738127 1.00742649 1.01569931
  0.99913071 1.02847068 1.01999051 1.01452852]]
[[-0.06727465 -0.15059117 -0.17261279 -0.13783286  0.39145958 -0.17821456
   0.09192239 -0.05568127 -0.10209594 -0.22403083]]


[1.273383801324438,
 0.7898426814459193,
 2.8824275221929785,
 -0.08056185287402501,
 -0.21695006033194686,
 -1.1665331455504682,
 0.415693170680881,
 0.7964526984506285,
 1.6368989471968765,
 1.8420370036125322]

In [54]:
optimal_point(df3, model=model, desired_class=0, original_class=1, threshold=10000,  chosen_row=1, point_epsilon=1e-3, epsilon=0.001)

C:\Users\Compuworld\AppData\Local\Temp\ipykernel_26024\3739720189.py:17: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  balanced_dataset = pd.concat([balanced_dataset, upsampled_class], ignore_index=True)


Class counts:
 50
1    1001
0    1001
Name: count, dtype: int64
Fitting model...
Model training complete.
boundary points started generation...
boundary points finished.
(10000, 50)
(9859, 50)
Finding the closest point from the contour line to the point...
Finding the closest point from the contour line to the point.
[[1.00121975 1.00085448 1.00051922 1.00128893 1.00133343 1.01037121
  1.00123322 1.00127281 1.00178975 1.00256707 0.99994755 1.00149282
  1.00019547 1.00143664 1.00080719 0.99419391 0.99825643 1.00125389
  1.0007409  1.00146426 1.00078981 1.00111834 1.00060389 1.00202889
  1.00034837 1.00430099 1.00144294 1.00126067 1.00124352 1.00083785
  1.00117119 1.00197254 0.99969272 1.00061753 1.00068402 1.00140935
  1.00173205 1.0006034  1.00184937 1.00223651 1.00118711 1.00556827
  1.00080768 1.00071868 0.99718239 1.11767977 1.00259458 1.00072438
  1.00075062 0.99984477]]
[[-4.55624159  6.87757279  2.08101321 -3.46555598 -3.00313904 -0.10781652
  -4.29312328 -3.67017985 -1.26849211

[6.482112566720399,
 8.189146673494657,
 -2.079973148595502,
 3.592128730790184,
 7.181037592103027,
 -5.325898052112336,
 -3.4285736348034574,
 2.7204293453651642,
 -15.76981772070797,
 -3.267680182765882,
 2.3349987552049285,
 -0.2178751405440591,
 -1.2339383624207563,
 -2.9963470331577207,
 5.690385006896312,
 0.24780023030534787,
 1.5462177368408683,
 -1.5322050938339133,
 1.3798693050971096,
 -3.5180753196561,
 0.6054213793664482,
 0.5630011948780975,
 0.6655928483355797,
 -0.3323332282212772,
 -0.3129007819539875,
 1.4185291631866803,
 1.1678928288046042,
 -2.064679396962676,
 3.2976326990937856,
 -0.3500920045402305,
 -2.5539847044963615,
 2.5140003041828005,
 -2.899886530006484,
 3.102082354179882,
 2.880572099782989,
 0.21553999375596256,
 4.212068128892092,
 -1.911618179867077,
 3.697560350049188,
 -0.06392802746019499,
 1.1361378975471466,
 -1.592985437361519,
 2.689557985245472,
 1.8358128470176052,
 -1.864533262898449,
 -2.8041797349941002,
 -1.559174033960624,
 -3.6735025

In [31]:
optimal_point(df3, model=model, desired_class=0, original_class=1, threshold=100000,  chosen_row=1, point_epsilon=1e-3, epsilon=0.001)

C:\Users\Compuworld\AppData\Local\Temp\ipykernel_1072\3739720189.py:17: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  balanced_dataset = pd.concat([balanced_dataset, upsampled_class], ignore_index=True)


Class counts:
 50
1    1001
0    1001
Name: count, dtype: int64
Fitting model...
Model training complete.
boundary points started generation...
[0.49940121 0.50059879]
boundary points finished.
(100000, 50)
(86747, 50)
Finding the closest point from the contour line to the point...
Finding the closest point from the contour line to the point.
[[1.00135084 1.00049196 0.99313969 1.00235241 1.00189257 1.0005754
  1.00126427 1.00121521 1.00088009 1.00142323 1.0015267  1.00117483
  1.00053331 1.00124124 1.0000099  1.00060338 1.00045256 1.00239249
  1.0007523  1.00171018 1.00026822 1.00130929 1.00276044 0.99354549
  1.00063392 0.98901913 1.00137441 0.99966791 1.00123223 1.00085398
  1.00189717 1.00144365 1.00050976 1.0019362  0.99833451 1.001199
  1.00133368 1.00069011 1.00687293 0.99978251 1.00124401 1.00166998
  1.00066897 0.99609629 1.00065861 1.00491045 1.00075109 1.00066734
  1.00073423 1.00420266]]
[[-2.85413101  1.96930043  0.1263486  -0.74115899 -1.12248625  2.35649649
  -3.78877122 

[8.185925129068703,
 3.2759664024513944,
 -4.036585044307226,
 6.31924905265672,
 9.063570471560746,
 -2.859110938240741,
 -2.923717255550797,
 1.737251846034681,
 -6.144789878291654,
 -4.995800827922947,
 -0.5194690541702454,
 -3.9160906188182976,
 -0.3323636474777443,
 -4.855121684481647,
 1.5055546441493286,
 2.6269125781455114,
 3.0113344057316334,
 1.6948358237087677,
 1.5578631410890496,
 -2.7706897190669806,
 -2.79244566129628,
 5.790339409394733,
 -2.433189494731324,
 0.7759539385204439,
 0.8865452178532469,
 1.8057232733235409,
 0.7538247058724248,
 2.531468485057286,
 3.097730223080217,
 0.33258584708537686,
 2.182462623843038,
 1.2857772075359915,
 -1.6224556045418237,
 -0.5880530633418115,
 0.08543830680335163,
 -2.3718285065365254,
 2.5779815180886927,
 -1.2047205205011413,
 4.706635936464857,
 1.5694263292053314,
 2.3846808390865233,
 -2.869212493333311,
 0.5064018657762661,
 -1.52164693666324,
 0.8080153142752629,
 -3.051716274783868,
 3.094761804996686,
 -4.296899626199

In [56]:
optimal_point(df3, model=model, desired_class=0, original_class=1, threshold=500000,  chosen_row=1, point_epsilon=1e-3, epsilon=0.001)

C:\Users\Compuworld\AppData\Local\Temp\ipykernel_26024\3739720189.py:17: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  balanced_dataset = pd.concat([balanced_dataset, upsampled_class], ignore_index=True)


Class counts:
 50
1    1001
0    1001
Name: count, dtype: int64
Fitting model...
Model training complete.
boundary points started generation...
boundary points finished.
(500000, 50)
(273136, 50)
Finding the closest point from the contour line to the point...
Finding the closest point from the contour line to the point.
[[1.00127878 1.00033207 0.99999672 1.00148981 1.00130684 1.00075432
  1.00053906 1.0012363  1.00088689 1.00170626 1.0015659  1.00139175
  0.99948826 1.00163702 1.0004766  1.00301182 1.00125997 1.00141754
  1.00709846 1.00179619 1.00068838 1.00119373 1.00292292 1.00155986
  1.00015391 1.00046207 1.00161523 1.00043274 1.00128009 1.00074093
  1.00149371 1.00148849 1.00001089 1.00150078 1.00075272 1.00016971
  1.00181881 0.99967782 0.99963903 1.00037185 1.00127704 1.00034128
  1.00165859 1.00080356 1.00027774 1.00596587 1.00225544 1.00075416
  1.00058089 0.99922006]]
[[-3.59163268  1.49765554  0.99672529 -2.04463438 -3.26332555  4.07345798
   2.17063613 -4.23715875  8.84863

[7.447686029059094,
 2.8038500301183182,
 -3.1653448332262566,
 5.014471049257585,
 6.920590918077879,
 -1.1404326645793414,
 3.0416502212904244,
 2.152883505090787,
 -5.642568989626538,
 -4.04700297161579,
 -0.3876943488908635,
 -0.7424304187836641,
 -1.8165651256364383,
 -2.274490199331856,
 2.407957564233491,
 -0.39748608078399084,
 -2.6732450183587804,
 0.014627501753083916,
 -2.651728801592241,
 -2.6182910355918896,
 -0.9462324459758036,
 3.8579161273250984,
 -2.3850977798266015,
 -1.148211931154926,
 -0.666327882594161,
 3.5847645625248274,
 1.8013700966447626,
 3.545644353812869,
 3.83490418235954,
 -2.6620201000587276,
 1.2697621735509528,
 1.493080377081787,
 -2.653330468688581,
 -1.5186652325678938,
 3.7615304674979075,
 3.870144862919391,
 4.357088673255783,
 -3.680233872052204,
 5.6134958247972,
 2.3415832974306845,
 2.8742854020275885,
 0.14748140278071165,
 -4.041926322342572,
 3.3746878396309468,
 -0.7396988902812227,
 -2.99725813318259,
 -1.7289260251798777,
 -3.2332005